### ISSUE TITLE
Epub conversion to audiobook fails

### ISSUE THREAD

**Issue by larry77** [DrewThomasson/ebook2audiobookXTTS#2]
Hello,

This is what happens on my platform (debian stable) when I try to convert an epub (in Italian).
Apologies for the bad formatting, but you get the idea.
Epub available at

https://e.pcloud.link/publink/show?code=XZpbqnZsp2qxNs7f1JgnFsMB6MDnkEnlLsy

`$ python ebook2audiobook.py /home/lorenzo/audiobook-generation/8_Ore_Italian_Edition-Gabriele_Gallo.epub 
starting...
Created directory: ./Working_files/Book
The file ./Working_files/temp.epub does not exist.
1% Converting input to HTML...
InputFormatPlugin: EPUB Input running
on /home/lorenzo/audiobook-generation/8_Ore_Italian_Edition-Gabriele_Gallo.epub
Found HTML cover titlepage.xhtml
Parsing all content...
34% Running transforms on e-book...
Merging user specified metadata...
Detecting structure...
Flattening CSS and remapping font sizes...
Source base font size is 12.00000pt
Removing fake margins...
Cleaning up manifest...
Trimming unused files from manifest...
Creating EPUB Output...
67% Running EPUB Output plugin `
`Splitting markup on page breaks and flow limits, if any...
	Looking for large trees in text/part0000_split_015.html...
	No large trees found
	Looking for large trees in text/part0000_split_023.html...
	No large trees found
	Looking for large trees in text/part0000_split_000.html...
	No large trees found
	Looking for large trees in text/part0000_split_004.html...
	No large trees found
	Looking for large trees in text/part0000_split_003.html...
	No large trees found
	Looking for large trees in text/part0000_split_005.html...
	No large trees found
	Looking for large trees in text/part0000_split_006.html...
	No large trees found
	Looking for large trees in text/part0000_split_012.html...
	No large trees found
	Looking for large trees in text/part0000_split_020.html...
	No large trees found
	Looking for large trees in text/part0000_split_017.html...
	No large trees found
	Looking for large trees in text/part0000_split_025.html...
	No large trees found
	Looking for large trees in text/part0000_split_028.html...
	No large trees found
	Looking for large trees in text/part0000_split_018.html...
	No large trees found
	Looking for large trees in text/part0000_split_026.html...
	No large trees found
	Looking for large trees in text/part0000_split_010.html...
	No large trees found
	Looking for large trees in text/part0000_split_019.html...
	No large trees found
	Looking for large trees in text/part0000_split_027.html...
	No large trees found
	Looking for large trees in text/part0000_split_007.html...
	No large trees found
	Looking for large trees in text/part0000_split_011.html...
	No large trees found
	Looking for large trees in text/part0000_split_002.html...
	No large trees found
	Looking for large trees in text/part0000_split_001.html...
	No large trees found
	Looking for large trees in text/part0000_split_008.html...
	No large trees found
	Looking for large trees in text/part0000_split_016.html...
	No large trees found
	Looking for large trees in text/part0000_split_024.html...
	No large trees found
	Looking for large trees in text/part0000_split_013.html...
	No large trees found
	Looking for large trees in text/part0000_split_021.html...
	No large trees found
	Looking for large trees in text/part0000_split_009.html...
	No large trees found
	Looking for large trees in text/part0000_split_029.html...
	No large trees found
	Looking for large trees in text/part0000_split_014.html...
	No large trees found
	Looking for large trees in text/part0000_split_022.html...
	No large trees found
	Looking for large trees in text/part0000_split_030.html...
	No large trees found 
`
EPUB output written to /home/lorenzo/ebook2audiobookXTTS/Working_files/temp.epub
Output saved to   /home/lorenzo/ebook2audiobookXTTS/Working_files/temp.epub
Created directory: ./Working_files/temp_ebook
Saved chapter: ./Working_files/temp_ebook/chapter_0.txt
Saved chapter: ./Working_files/temp_ebook/chapter_1.txt
Saved chapter: ./Working_files/temp_ebook/chapter_2.txt
Saved chapter: ./Working_files/temp_ebook/chapter_3.txt
Saved chapter: ./Working_files/temp_ebook/chapter_4.txt
Saved chapter: ./Working_files/temp_ebook/chapter_5.txt
Saved chapter: ./Working_files/temp_ebook/chapter_6.txt
Saved chapter: ./Working_files/temp_ebook/chapter_7.txt
Saved chapter: ./Working_files/temp_ebook/chapter_8.txt
Saved chapter: ./Working_files/temp_ebook/chapter_9.txt
Saved chapter: ./Working_files/temp_ebook/chapter_10.txt
Saved chapter: ./Working_files/temp_ebook/chapter_11.txt
Saved chapter: ./Working_files/temp_ebook/chapter_12.txt
Saved chapter: ./Working_files/temp_ebook/chapter_13.txt
Saved chapter: ./Working_files/temp_ebook/chapter_14.txt
[nltk_data] Downloading package punkt to /home/lorenzo/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
./Working_files/temp_ebook||||./Chapter_wav_files|||||None
 > tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
Chapter 0:   0%|                                         | 0/15 [00:00<?, ?it/s]Generating fragment: 
```

 Quest’opera è protetta dal diritto d’autore e riservata....
 > Text splitted to sentences.
['Quest’opera è protetta dal diritto d’autore e riservata.']
 > Processing time: 23.16238522529602
 > Real-time factor: 3.1218251480304233
Chapter 0:   7%|██▏                              | 1/15 [00:23<05:24, 23.19s/it]Generating fragment: Ogni uso improprio o diffusione dell’opera o di parti di essa tramite supporto meccanico, elettronico o altro, traduzione e rappresentazione in pubblico senza il consenso dell’editore e dell’autore è vietato e sarà perseguito....
 > Text splitted to sentences.
['Ogni uso improprio o diffusione dell’opera o di parti di essa tramite supporto meccanico, elettronico o altro, traduzione e rappresentazione in pubblico senza il consenso dell’editore e dell’autore è vietato e sarà perseguito.']
 > Processing time: 17.506171226501465
 > Real-time factor: 0.6752411828352971
Chapter 0:  13%|████▍                            | 2/15 [00:40<04:18, 19.90s/it]Generating fragment: Questo libro è un’opera di fantasia....
 > Text splitted to sentences.
['Questo libro è un’opera di fantasia.']
 > Processing time: 3.1612229347229004
 > Real-time factor: 0.6390729583269763
Chapter 0:  20%|██████▌                          | 3/15 [00:43<02:27, 12.26s/it]Generating fragment: Personaggi e luoghi citati sono invenzioni dell’autore e hanno lo scopo di conferire veridicità alla narrazione....
 > Text splitted to sentences.
['Personaggi e luoghi citati sono invenzioni dell’autore e hanno lo scopo di conferire veridicità alla narrazione.']
 > Processing time: 8.189717292785645
 > Real-time factor: 0.6616904581180874
Chapter 0:  27%|████████▊                        | 4/15 [00:52<01:57, 10.67s/it]Generating fragment: Qualsiasi analogia con fatti, luoghi e persone, vive o scomparse, è assolutamente casuale....
 > Text splitted to sentences.
['Qualsiasi analogia con fatti, luoghi e persone, vive o scomparse, è assolutamente casuale.']
 > Processing time: 5.9798264503479
 > Real-time factor: 0.6502760456786633
Chapter 0:  33%|███████████                      | 5/15 [00:58<01:56, 11.64s/it]
Traceback (most recent call last):
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 440, in <module>
    convert_chapters_to_audio(chapters_directory, output_audio_directory, target_voice, language)
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 405, in convert_chapters_to_audio
    fragments = split_long_sentence(sentence)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 365, in split_long_sentence
    return split_long_sentence(first_half, max_length, max_pauses) + split_long_sentence(second_half, max_length, max_pauses)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 365, in split_long_sentence
    return split_long_sentence(first_half, max_length, max_pauses) + split_long_sentence(second_half, max_length, max_pauses)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 365, in split_long_sentence
    return split_long_sentence(first_half, max_length, max_pauses) + split_long_sentence(second_half, max_length, max_pauses)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 992 more times]
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 355, in split_long_sentence
    closest_split = min(possible_splits, key=lambda x: abs(x - middle_index))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 355, in <lambda>
    closest_split = min(possible_splits, key=lambda x: abs(x - middle_index))
                                                       ^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by DrewThomasson** [comment]
I see, Italian, I'll try to add a fix for this and get a specialized sentence splitting method that works with Italian for you,

Also anyway I could see that epub your trying to convert to test in my end?

-Oh btw just saying cause I didn't see it in your terminal message but to use other languages you have to do it in this format or else it'll just make a English speaker try to say all of the stuff.


## With Language Specification(Optional):
```bash
python ebook2audiobook.py <path_to_ebook_file> [path_to_voice_file] [language_code]
```
Replace <path_to_ebook_file> with the path to your eBook file.
Optionally, include <path_to_voice_file> for voice cloning.
Optionally, include <language_code> to specify the language (default is "en" for English).

## Supported Languages with their respective codes

The script supports the following languages for text-to-speech conversion:

English (en),
Spanish (es),
French (fr),
German (de),
Italian (it),
Portuguese (pt),
Polish (pl),
Turkish (tr),
Russian (ru),
Dutch (nl),
Czech (cs),
Arabic (ar),
Chinese (zh-cn),
Japanese (ja),
Hungarian (hu),
Korean (ko)

Specify the language code when running the script to use these languages.

**Comment by DrewThomasson** [comment]
## Fixed
- Should work for you now just make sure to specify the language like in the readme guide for Italian
- Example of me using it on the test Italian dantes inferno for italian`python ebook2audiobook.py italian_test.txt default_voice.wav it`
## Update Log

### Testing Update
- Testing Italian Dante's Inferno on my laptop overnight. lol
- Seems to be working fine
- git pull and you should be good to go

### Fixes and Changes

- **Sentence Splitting Issue for Italian:** The sentence splitting wasn't working for Italian because it wasn't set in NLTK. Added the option for "it" (Italian) to use a non-recursive method to split sentences.
- **Improvement:** Swapped out the recursive sentence splitter for a non-recursive splitter method to avoid the recursive limit issue.

### Rehash of Usage Instructions

#### With Language Specification (Optional):
```bash
python ebook2audiobook.py <path_to_ebook_file> [path_to_voice_file] [language_code]
```
- **Replace** `<path_to_ebook_file>` with the path to your eBook file.
- **Optionally include** `<path_to_voice_file>` for voice cloning.
- **Optionally include** `[language_code]` to specify the language (default is "en" for English).

#### Supported Languages with Their Respective Codes:

- English (en)
- Spanish (es)
- French (fr)
- German (de)
- Italian (it)
- Portuguese (pt)
- Polish (pl)
- Turkish (tr)
- Russian (ru)
- Dutch (nl)
- Czech (cs)
- Arabic (ar)
- Chinese (zh-cn)
- Japanese (ja)
- Hungarian (hu)
- Korean (ko)

Specify the language code when running the script to use these languages.

---

**Comment by larry77** [comment]
Thanks!
I made a git pull, but I still have issues -- see below.
```

> tts_models/multilingual/multi-dataset/xtts_v2 is already downloaded.
 > Using model: xtts
Chapter 0:   0%|                                         | 0/15 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 443, in <module>
    convert_chapters_to_audio(chapters_directory, output_audio_directory, target_voice, language)
  File "/home/lorenzo/ebook2audiobookXTTS/ebook2audiobook.py", line 408, in convert_chapters_to_audio
    for fragment in fragments:
                    ^^^^^^^^^
UnboundLocalError: cannot access local variable 'fragments' where it is not associated with a value

```

**Comment by DrewThomasson** [comment]
Here I think i fixed it, try a git pull again and attempt at running it again

`python ebook2audiobook.py 8_Ore_Italian_Edition-Gabriele_Gallo.epub default_voice.wav it`

**Comment by larry77** [comment]
Hi!
Something still goes wrong.
The task is allegedly completed within a few seconds, but the audiobook is empty.
I enclose a full log of my bash output as a text file.

[audio.log](https://github.com/DrewThomasson/ebook2audiobookXTTS/files/14500551/audio.log)

**Comment by DrewThomasson** [comment]
It might have to do with the cleanup script I added,...

Try reverting to the previous commit where I only fixed the first issue you were having and tell me how it goes 

With the command;

'git pull origin cb7fc7880581840505b58401e209011905ca2a7e'

**Comment by DrewThomasson** [comment]
Actually I think I see the issue in your log, You appear to be not including the specified voice to clone when calling the program.

I see your command being `python ebook2audiobook.py /home/lorenzo/audiobook-generation/8_Ore_Italian_Edition-Gabriele_Gallo.epub it` 
-Your missing the specified voice parameter leading to issues, 


When it should be `python ebook2audiobook.py /home/lorenzo/audiobook-generation/8_Ore_Italian_Edition-Gabriele_Gallo.epub default_voice.wav it`

**Comment by larry77** [comment]
Now it works and I can close this. Thanks!
